find_package(MPI)

if (CMAKE_CUDA_COMPILER OR CMAKE_HIP_COMPILER)
    add_library(cluster_gpu OBJECT cluster_gpu.cu halo_gpu.cu)
    target_include_directories(cluster_gpu PRIVATE ${CSTONE_DIR} ${SPH_DIR} ${MPI_CXX_INCLUDE_PATH})
    if (CMAKE_CUDA_COMPILER)
        target_link_libraries(cluster_gpu PRIVATE CUDA::cudart ${MPI_CXX_LIBRARIES})
        target_compile_definitions(cluster_gpu PRIVATE USE_CUDA)
    else ()
        target_link_libraries(cluster_gpu PRIVATE hip::host ${MPI_CXX_LIBRARIES})
        target_compile_definitions(cluster_gpu PRIVATE THRUST_DEVICE_SYSTEM=THRUST_DEVICE_SYSTEM_HIP)
        set_target_properties(${exename} PROPERTIES LINKER_LANGUAGE CXX)
    endif ()
endif ()